services:
  frontend:
    build:
      context: ./Frontend
    container_name: pico-placa-frontend
    ports:
      - "3004:80"
backend:
    build:
      context: ./Backend
    container_name: pico-placa-backend
    ports:
      - "3504"